on: [push, pull_request]

name: CI

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions: {}
jobs:
  "Linux_Compile_Naev":
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_type: debug
          - build_type: release
    uses: "naev/naev/.github/workflows/compile_naev.yml@main"
    with:
      platform: "linux"
      build_type: "${{ matrix.build_type }}"
      release: false

  "Windows_Compile_Naev":
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_type: debug
          - build_type: release
    uses: "naev/naev/.github/workflows/compile_naev.yml@main"
    with:
      platform: "windows"
      build_type: "${{ matrix.build_type }}"
      release: false

  "Darwin_Compile_Naev":
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        include:
          - build_type: debug
          - build_type: release
    uses: "naev/naev/.github/workflows/compile_naev.yml@main"
    with:
      platform: "macos"
      build_type: "${{ matrix.build_type }}"
      release: false

  "Documentation":
    permissions:
      contents: write
    uses: "naev/naev/.github/workflows/compile_naev.yml@main"
    with:
      platform: "docs"
      build_type: "debug"
      release: false